UU-ER/AdOpT-NET0

data/technology_data/CO2Capture/DAC_Adsorption.json, src/components/technologies/specificTechnologies/dac_adsorption.py, src/test/technology_data/TestTec_DAC_Adsorption.json
DAC had CO2 as a carrier, now CO2 captured
- adapted in tests, jsons and code
=> DAC bugs fixed

src/components/technologies/genericTechnologies/res.py
in res.py, capfactor was allocated to operation and not design
- fixed
=> RES result writing bug fixed

src/components/technologies/specificTechnologies/heat_pump.py, src/data_preprocessing/data_loading.py, src/test/technology_data/TestTec_DAC_Adsorption.json
- Bounds were not calculated correctly for heat pump
- DAC Adsorption test adapted to exclude ohmic heating
=> Bug fix heat pump/dac test

docs/source/src_code/data_preparation/model_configuration/monte_carlo.rst, docs/source/src_code/data_preparation/model_configuration/pareto.rst, docs/source/workflow/DefineModelConfiguration.rst, main.py, src/components/networks/network.py, src/components/technologies/technology.py, src/components/technologies/utilities.py, src/data_management/handle_input_data.py, src/data_preprocessing/template_creation.py, src/energyhub.py, src/model_construction/__init__.py, src/model_construction/construct_balances.py, src/model_construction/construct_nodes.py, src/model_construction/utilities.py, src/result_management/read_results.py, src/result_management/save_results.py, src/test/case_study_full_pipeline/ConfigModel.json, src/test/case_study_full_pipeline/MonteCarlo.csv, src/test/test_full_model_flow.py, src/utilities.py
monte carlo implemented for:
- technology costs
- network costs
- import/export prices
MISSING: Testing
=> Monte carlo fully implemented

data/technology_data/Industrial/CrackerFurnace.json, data/technology_data/Industrial/CrackerFurnace_Electric.json, data/technology_data/Industrial/EthyleneCompression.json, data/technology_data/Industrial/EthyleneCompression_Electric.json, data/technology_data/Industrial/EthyleneSeparation.json
Checked the data and included DOI
=> Update industry technologies

src/components/technologies/technology.py, src/data_management/__init__.py, src/data_preprocessing/template_creation.py, src/energyhub.py, src/logger.py, src/test/test_preprocessing.py, src/test/utilities.py
See commits for changes
#208 
#207 
#204
=> Resolve small issues

src/components/technologies/genericTechnologies/res.py
=> bug capfactor fixed

src/components/technologies/genericTechnologies/conv1.py, src/components/technologies/genericTechnologies/conv2.py, src/components/technologies/genericTechnologies/conv3.py
use correct set_t in generic technologies
=> set_t correction

src/components/technologies/genericTechnologies/conv3.py
fix bug with conv3 in standby power
=> Conv3 with correct standbycarrier

adopt_net0/components/technologies/genericTechnologies/sink.py
- tsa for sink was not working -> fixed with the same method as in stor.py
=> Bug fix in sink

adopt_net0/components/technologies/genericTechnologies/stor.py
Storage wasnt working, since capex functions were not overwritten. Change required due to monte carlo implementation
=> Storage fixed

adopt_net0/components/technologies/genericTechnologies/sink.py, adopt_net0/components/technologies/genericTechnologies/stor.py
=> Bug: Parameter initialization with dict keys

tests/test_technologies.py
=> Fixed DAC test

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
For
- feature requests
- bug reports
=> Implemented Issue templates

.github/workflows/00develop.yml, .github/workflows/testing.yml, README.md, pyproject.toml
- added codecov as a test coverage app
- added badge to readme file
=> Add codecov as a code coverage app

docs/source/index.rst, docs/source/workflow/LoadData.rst
- improved network description
- made case studies more visable
=> Improve network documentation

adopt_net0/model_construction/construct_nodes.py, docs/source/case_studies/CaseStudy_DAC.ipynb
Deleted TODO in construct_nodes.py line 49 and fixed documentation and comments on DAC case study
=> Deleted TODO in construct_nodes.py line 49 and fixed DAC case study

tests/test_preprocessing.py
- Made sure CCS in TestTecs is tested
- Added test for copy_network_data
=> Small fixes in testing

joss_submission/paper.bib, joss_submission/paper.md
Added citation of path dependencies to paper (pvlib, pyomo, tsam)
=> added dependencies citation

adopt_net0/model_construction/construct_balances.py
Carbon subsidy was not assigned for negative emissions from carriers
=> Added carbon revenues from carriers

adopt_net0/components/component.py, adopt_net0/components/networks/__init__.py, adopt_net0/components/networks/genericNetworks/__init__.py, adopt_net0/components/networks/genericNetworks/electricity.py, adopt_net0/components/networks/genericNetworks/fluid.py, adopt_net0/components/networks/network.py, adopt_net0/data/network_data/electricityOffshore.json, adopt_net0/data/network_data/electricityOnshore.json, adopt_net0/data/network_data/electricitySimple.json, adopt_net0/data_management/handle_input_data.py, adopt_net0/data_management/utilities.py, adopt_net0/model_construction/construct_nodes.py, adopt_net0/model_construction/utilities.py, tests/test_full_model_flow.py, tests/test_networks.py, tests/test_technologies.py
Cleaning and:
- electricity networks are always bi-directional
- removed printing in handle_input_data.py
- fixed comments on PR #407
=> Clean and small bug fixes - splitting networks
